# -*- coding: utf-8 -*-
"""healthcare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPQ1xIO6Svsm-M1QMIp2l5BaU65_EUq-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# -------------------------------
# 1. Create Synthetic Data
# -------------------------------
np.random.seed(1)

n = 10000

data = pd.DataFrame({
    "Patient_ID": range(1, n+1),
    "Age": np.random.randint(20, 81, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Blood_Pressure": np.random.randint(80, 181, n),
    "Sugar_Level": np.random.randint(70, 201, n),
    "Cholesterol": np.random.randint(150, 301, n),
    "Heart_Rate": np.random.randint(60, 121, n)
})

print("First 5 rows:\n", data.head())

# -------------------------------
# 2. Heart Rate Analysis
# -------------------------------
def heart_rate_status(hr):
    if hr <= 100:
        return "Normal"
    else:
        return "High"

data["HR_Status"] = data["Heart_Rate"].apply(heart_rate_status)

# -------------------------------
# 3. Risk Classification
# -------------------------------
def risk_level(row):
    if (row["Blood_Pressure"] > 140 or
        row["Sugar_Level"] > 160 or
        row["Cholesterol"] > 240 or
        row["Heart_Rate"] > 100):
        return "High"
    else:
        return "Low"

data["Risk_Level"] = data.apply(risk_level, axis=1)

# -------------------------------
# 4. Age Group
# -------------------------------
data["Age_Group"] = pd.cut(data["Age"],
                          bins=[20,40,60,80],
                          labels=["Young","Middle","Senior"])

# -------------------------------
# 5. Basic Analysis
# -------------------------------
print("\nAverage Values:\n", data.mean(numeric_only=True))

print("\nGender Count:\n", data["Gender"].value_counts())

print("\nRisk Count:\n", data["Risk_Level"].value_counts())

# -------------------------------
# 6. Visualization
# -------------------------------

# Bar Chart - Risk
data["Risk_Level"].value_counts().plot(kind="bar")
plt.title("Risk Level Distribution")
plt.show()

# Pie Chart - Gender
data["Gender"].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.title("Gender Distribution")
plt.show()

# Histogram - Age
plt.hist(data["Age"])
plt.title("Age Distribution")
plt.show()

# Scatter Plot - BP vs Age
plt.scatter(data["Age"], data["Blood_Pressure"])
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.title("BP vs Age")
plt.show()

# Box Plot - Cholesterol
plt.boxplot(data["Cholesterol"])
plt.title("Cholesterol Distribution")
plt.show()

# Heatmap (Simple)
corr = data.corr(numeric_only=True)
plt.imshow(corr)
plt.colorbar()
plt.title("Correlation Heatmap")
plt.show()